server:
  port: 8088

logging:
  level:
    org.springframework: DEBUG

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
      generate-ddl: true
      defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  message:
    basename: messages
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#  security:
#    user:
#      name: username
#      password: passw0rd

management:
  endpoints:
    web:
      exposure:
        include: "*"


